### ISSUE TITLE
Redacts the user's own identify on github PRs.

### ISSUE THREAD

**Issue by rillian** [zombie/blind-reviews#11]
Hi. Thanks for adding github support! One thing I've noticed is that it redacts a PR author's identity even when the author is myself, which is confusing. It makes me think I need to review the changes.

Is it possible to exempt the user's identity on Github the way it is on Bugzilla?

**Comment by zombie** [comment]
Hey, thanks for trying and reporting the issue.  I just released version 1.1 to AMO with new rules: all PRs are blind by default, except for 1) user's own, 2) merged/closed, or 3) already approved by the user.

This is not as specific as I originally planned (see canceled pull #10), and currently uses only info already present on the PR page, but I think it hits the 80% mark for common use cases, enough to be useful and not too annoying.

Please test it out for a few days, and let me know if you notice any patterns when it could be more specific, as I would like to revisit this logic at a later point.

**Comment by rillian** [comment]
Thanks for the quick fix. Working better so far!
