### ISSUE TITLE
User's own identity redacted in issue search list

### ISSUE THREAD

**Issue by rillian** [zombie/blind-reviews#16]
If I search for issues with an `author:` restriction on Github, my own PR is listed with a redacted submitter. E.g. https://github.com/rust-lang/rust/pulls/rillian lists my PR as 'opened ... by [redacted]'.

Another context that needs an exception?

**Comment by zombie** [comment]
Yeah, that was supposed to go through the same logic that used the github REST api, and now needs the same exception from PR #11.  I'll try to get to it this week while in Austin.
