### ISSUE TITLE
Commit authors still visible in GitHub

### ISSUE THREAD

**Issue by tie-rack** [zombie/blind-reviews#26]
Commits listed in a PR display the author's avatar and username.

<img width="544" alt="screen shot 2018-03-08 at 1 58 21 pm" src="https://user-images.githubusercontent.com/3526/37170518-04ddc450-22d9-11e8-9b96-14fc1693154b.png">

**Comment by zombie** [comment]
Uh, something probably changed in the Github html structure, and the tests are not running because of an upstream issue (atti187/wdio-chromedriver-service#11).

Thanks for reporting this.  I'll get it fixed, and also find another way we run tests.  :\

**Comment by zombie** [comment]
Fixed version available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/blind-reviews/), please let me know if you notice anything else not working.

**Comment by tie-rack** [comment]
Awesome, thank you!
