### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by joymallyac** [zombie/blind-reviews#35]
The extension is not working in Mozilla(GitHub) from last 5-6 days.

**Comment by zombie** [comment]
Can you please give more details on what exactly isn't working?  Which page or pull request?  Also, which extension version do you have installed?

**Comment by joymallyac** [comment]
I am using version 1.4.0.  It is working fine for pull requests. It is not working in case of issues in GitHub. 
![capture1](https://user-images.githubusercontent.com/24983792/38168922-26435fbc-3529-11e8-95d6-355214f18abf.PNG)
![capture2](https://user-images.githubusercontent.com/24983792/38168924-2a40d324-3529-11e8-8abc-792b0bd8513f.PNG)

**Comment by zombie** [comment]
It was never designed to work on issues.  What would be the reason to redact the issue author?

**Comment by joymallyac** [comment]
oops! I thought it would work for issues too. No problem, it's my fault! Thanks for making me aware.
